<a href="https://colab.research.google.com/github/Venky404/Google-Colab-Assignment/blob/main/Session_13_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Q1 - Basic Array Creation

import numpy as np

# Creating a 1D array
array1 = np.array([10, 20, 30, 40, 50])

# Creating a 3x3 2D array
array2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Displaying the arrays
print("1D Array:")
print(array1)
print("Shape:", array1.shape)
print("Data Type:", array1.dtype)

print("\n2D Array:")
print(array2)
print("Shape:", array2.shape)
print("Data Type:", array2.dtype)

1D Array:
[10 20 30 40 50]
Shape: (5,)
Data Type: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data Type: int64


In [3]:
# Q2 - Zeros and Ones Arrays

import numpy as np

# 1D array of 8 zeros
zeros_array = np.zeros(8)

# 4x4 array of ones
ones_array = np.ones((4, 4))

# 3x3 matrix of zeros
matrix_zeros = np.zeros((3, 3))

# Displaying the arrays
print("1D Array of 8 Zeros:")
print(zeros_array)

print("\n4x4 Array of Ones:")
print(ones_array)

print("\n3x3 Matrix of Zeros:")
print(matrix_zeros)

1D Array of 8 Zeros:
[0. 0. 0. 0. 0. 0. 0. 0.]

4x4 Array of Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# Q3 - Using np.arange()

import numpy as np

# Numbers from 0 to 20
array1 = np.arange(0, 21, 1)

# Even numbers from 10 to 50
array2 = np.arange(10, 51, 2)

# Numbers from 5 to 100 with step of 5
array3 = np.arange(5, 101, 5)

# Displaying the arrays
print("Numbers from 0 to 20:")
print(array1)

print("\nEven Numbers from 10 to 50:")
print(array2)

print("\nNumbers from 5 to 100 (Step = 5):")
print(array3)

Numbers from 0 to 20:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Even Numbers from 10 to 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

Numbers from 5 to 100 (Step = 5):
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [5]:
# Q4 - Using np.linspace()

import numpy as np

# 10 equally spaced numbers between 0 and 5
array1 = np.linspace(0, 5, 10)

# 15 equally spaced numbers between -10 and 10
array2 = np.linspace(-10, 10, 15)

# Display the arrays
print("10 Equally Spaced Numbers (0 to 5):")
print(array1)
print("Length:", len(array1))

print("\n15 Equally Spaced Numbers (-10 to 10):")
print(array2)
print("Length:", len(array2))

10 Equally Spaced Numbers (0 to 5):
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 10

15 Equally Spaced Numbers (-10 to 10):
[-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length: 15


In [6]:
# Q5 - Random Arrays

import numpy as np

# Random numbers between 0 and 1
array1 = np.random.rand(10)

# 3x3 matrix from standard normal distribution
array2 = np.random.randn(3, 3)

# 4x5 matrix of random integers between 10 and 50
array3 = np.random.randint(10, 51, size=(4, 5))

# Display the arrays
print("Random Numbers (0 to 1):")
print(array1)

print("\n3x3 Matrix (Standard Normal Distribution):")
print(array2)

print("\n4x5 Random Integer Matrix (10 to 50):")
print(array3)

Random Numbers (0 to 1):
[0.04231245 0.75770231 0.95226458 0.40220865 0.77899645 0.44421219
 0.60119608 0.18502602 0.05665521 0.23624764]

3x3 Matrix (Standard Normal Distribution):
[[-1.05169999 -0.17802484 -1.32470202]
 [ 0.61997463  1.00705169  0.95122662]
 [ 0.31381584 -0.14376264 -0.03659731]]

4x5 Random Integer Matrix (10 to 50):
[[47 24 31 29 34]
 [47 49 20 36 17]
 [30 24 39 19 28]
 [47 35 15 49 40]]


In [7]:
# Q6 - Vector Operations

import numpy as np

# Creating vectors
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])

# Operations
addition = v1 + v2
subtraction = v1 - v2
multiplication = v1 * v2
dot_product = np.dot(v1, v2)

# Display results
print("Vector 1:", v1)
print("Vector 2:", v2)

print("\nAddition:")
print(addition)

print("\nSubtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nDot Product:")
print(dot_product)

Vector 1: [2 4 6 8]
Vector 2: [1 3 5 7]

Addition:
[ 3  7 11 15]

Subtraction:
[1 1 1 1]

Element-wise Multiplication:
[ 2 12 30 56]

Dot Product:
100


In [8]:
# Q7 - Matrix Operations

import numpy as np

# Creating two 3x3 matrices
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

# Matrix Addition
addition = A + B

# Matrix Multiplication
multiplication = A @ B

# Element-wise Multiplication
elementwise = A * B

# Display the matrices
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix Addition:")
print(addition)

print("\nMatrix Multiplication:")
print(multiplication)

print("\nElement-wise Multiplication:")
print(elementwise)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [9]:
# Q8 - Properties of Arrays

import numpy as np

# Creating a 4x4 matrix of random integers
matrix = np.random.randint(1, 101, size=(4, 4))

# Display the matrix
print("Random 4x4 Matrix:")
print(matrix)

# Displaying properties
print("\nShape:", matrix.shape)
print("Dimension (ndim):", matrix.ndim)
print("Total Elements (size):", matrix.size)
print("Data Type:", matrix.dtype)
print("Minimum Value:", matrix.min())
print("Maximum Value:", matrix.max())

Random 4x4 Matrix:
[[39 40 53 79]
 [46 83 11 11]
 [34 34  3 94]
 [40 89 27 38]]

Shape: (4, 4)
Dimension (ndim): 2
Total Elements (size): 16
Data Type: int64
Minimum Value: 3
Maximum Value: 94


In [10]:
# Q9 - Random + Reshape + Statistics

import numpy as np

# Generate 20 random integers between 1 and 50
array = np.random.randint(1, 51, 20)

# Reshape into a 4x5 matrix
matrix = array.reshape(4, 5)

# Display the matrix
print("4x5 Matrix:")
print(matrix)

# Statistics
print("\nSum of all elements:", np.sum(matrix))
print("Mean:", np.mean(matrix))
print("Standard Deviation:", np.std(matrix))

# Maximum value in each row
print("\nMaximum Value in Each Row:")
print(np.max(matrix, axis=1))

4x5 Matrix:
[[39 18  5 48 28]
 [23 37 47 40 33]
 [ 3 16 29 43  5]
 [36 37 42 42  1]]

Sum of all elements: 572
Mean: 28.6
Standard Deviation: 15.114231703927262

Maximum Value in Each Row:
[48 47 43 42]


In [11]:
# Q10 - Simple Statistics Calculator

import numpy as np

try:
    # Ask the user for the number of random values
    count = int(input("Enter how many random numbers you want to generate: "))

    if count <= 0:
        print("Please enter a number greater than 0.")

    else:
        # Generate random numbers between 10 and 100
        numbers = np.random.randint(10, 101, count)

        # Display the array
        print("\nGenerated Numbers:")
        print(numbers)

        # Statistics
        print("\nMean:", np.mean(numbers))
        print("Median:", np.median(numbers))
        print("Standard Deviation:", np.std(numbers))
        print("Minimum:", np.min(numbers))
        print("Maximum:", np.max(numbers))

        # Reshape into 2D array if possible
        if count % 2 == 0:
            matrix = numbers.reshape(2, count // 2)

            print("\nReshaped 2D Array:")
            print(matrix)

            print("\nRow-wise Sum:")
            print(np.sum(matrix, axis=1))
        else:
            print("\nArray cannot be reshaped into a 2D matrix with 2 rows.")

except ValueError:
    print("Invalid input! Please enter a valid integer.")
except Exception as e:
    print("An error occurred:", e)

Enter how many random numbers you want to generate: 8

Generated Numbers:
[97 64 80 11 67 18 96 88]

Mean: 65.125
Median: 73.5
Standard Deviation: 31.36254732957768
Minimum: 11
Maximum: 97

Reshaped 2D Array:
[[97 64 80 11]
 [67 18 96 88]]

Row-wise Sum:
[252 269]
