<a href="https://colab.research.google.com/github/Venky404/Google-Colab-Assignment/blob/main/Session_14_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Q1. Array Properties

In [1]:
# Import NumPy library
import numpy as np

# Create a 2D array of shape (5, 6) with random integers between 10 and 100
arr = np.random.randint(10, 101, size=(5, 6))

# Display the array
print("Generated Array:\n")
print(arr)

# Display array properties
print("\nShape of the array:", arr.shape)
print("Total number of elements:", arr.size)
print("Data type:", arr.dtype)

Generated Array:

[[71 21 80 99 60 71]
 [12 33 71 24 17 49]
 [66 77 54 69 20 10]
 [76 12 54 48 18 94]
 [40 93 92 14 58 25]]

Shape of the array: (5, 6)
Total number of elements: 30
Data type: int64


## Q2. Statistical Methods - Basic

In [2]:
# Import NumPy library
import numpy as np

# Generate 20 random integers between 1 and 50
arr = np.random.randint(1, 51, size=20)

# Display the array
print("Generated Array:\n")
print(arr)

# Minimum value and its index
print("\nMinimum value:", arr.min())
print("Index of minimum value:", arr.argmin())

# Maximum value and its index
print("\nMaximum value:", arr.max())
print("Index of maximum value:", arr.argmax())

# Sum of all elements
print("\nSum of all elements:", arr.sum())

# Mean and Standard Deviation
print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())

Generated Array:

[29 24  6  8 31 19 16 22 36 12 19  6 14 23 40  4 37 20 24 33]

Minimum value: 4
Index of minimum value: 15

Maximum value: 40
Index of maximum value: 14

Sum of all elements: 423
Mean: 21.15
Standard Deviation: 10.593748156342023


## Q3. Statistical Methods on 2D Array

In [3]:
# Import NumPy library
import numpy as np

# Create a 4x5 matrix with random integers between 20 and 80
matrix = np.random.randint(20, 81, size=(4, 5))

# Display the matrix
print("Generated Matrix:\n")
print(matrix)

# Display overall statistics
print("\nMinimum value:", matrix.min())
print("Maximum value:", matrix.max())
print("Sum of all elements:", matrix.sum())
print("Mean:", matrix.mean())
print("Standard Deviation:", matrix.std())

# Sum of each row
print("\nRow-wise Sum:")
print(matrix.sum(axis=1))

# Sum of each column
print("\nColumn-wise Sum:")
print(matrix.sum(axis=0))

Generated Matrix:

[[34 72 71 69 26]
 [64 29 53 47 20]
 [45 43 41 37 20]
 [59 58 54 32 47]]

Minimum value: 20
Maximum value: 72
Sum of all elements: 921
Mean: 46.05
Standard Deviation: 15.935730293902443

Row-wise Sum:
[272 213 186 250]

Column-wise Sum:
[202 202 219 185 113]


## Q4. Reshape

In [4]:
# Import NumPy library
import numpy as np

# Create a 1D array from 1 to 24
arr = np.arange(1, 25)

# Display the original array
print("Original Array:")
print(arr)

# Reshape into (4, 6)
arr1 = arr.reshape(4, 6)
print("\nArray with shape (4, 6):")
print(arr1)
print("Shape:", arr1.shape)

# Reshape into (3, 8)
arr2 = arr.reshape(3, 8)
print("\nArray with shape (3, 8):")
print(arr2)
print("Shape:", arr2.shape)

# Reshape into (2, 3, 4)
arr3 = arr.reshape(2, 3, 4)
print("\nArray with shape (2, 3, 4):")
print(arr3)
print("Shape:", arr3.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Array with shape (4, 6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

Array with shape (3, 8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)

Array with shape (2, 3, 4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


## Q5. NumPy Indexing (1D & 2D)

In [5]:
# Import NumPy library
import numpy as np

# Create the given array
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

# Display the array
print("Original Array:")
print(arr)

# Extract the first row
print("\nFirst Row:")
print(arr[0])

# Extract the last column
print("\nLast Column:")
print(arr[:, -1])

# Extract the center 2x2 submatrix
print("\nCenter 2x2 Submatrix:")
print(arr[0:2, 1:3])

# Extract all even numbers using boolean indexing
print("\nEven Numbers:")
print(arr[arr % 2 == 0])

Original Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

First Row:
[10 20 30 40]

Last Column:
[ 40  80 120]

Center 2x2 Submatrix:
[[20 30]
 [60 70]]

Even Numbers:
[ 10  20  30  40  50  60  70  80  90 100 110 120]


## Q6. Advanced Indexing

In [6]:
# Import NumPy library
import numpy as np

# Create a 5x5 matrix with random integers between 1 and 100
matrix = np.random.randint(1, 101, size=(5, 5))

# Display the original matrix
print("Original Matrix:")
print(matrix)

# Print diagonal elements
print("\nDiagonal Elements:")
print(np.diag(matrix))

# Print elements greater than 50
print("\nElements Greater Than 50:")
print(matrix[matrix > 50])

# Replace elements less than 30 with 0
matrix[matrix < 30] = 0

# Display the modified matrix
print("\nModified Matrix:")
print(matrix)

Original Matrix:
[[ 83   9   6  96  57]
 [ 17  84  49  14  73]
 [ 51  97  46  27 100]
 [ 18  69  16  26  28]
 [ 23  32  22  13   9]]

Diagonal Elements:
[83 84 46 26  9]

Elements Greater Than 50:
[ 83  96  57  84  73  51  97 100  69]

Modified Matrix:
[[ 83   0   0  96  57]
 [  0  84  49   0  73]
 [ 51  97  46   0 100]
 [  0  69   0   0   0]
 [  0  32   0   0   0]]


## Q7. Arithmetic Operations

In [7]:
# Import NumPy library
import numpy as np

# Create two arrays
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

# Display the arrays
print("Array A:", a)
print("Array B:", b)

# Perform arithmetic operations
print("\nAddition:")
print(a + b)

print("\nSubtraction:")
print(a - b)

print("\nMultiplication:")
print(a * b)

print("\nDivision:")
print(a / b)

print("\nElement-wise Power:")
print(a ** b)

print("\nModulo Operation:")
print(a % b)

Array A: [10 20 30 40]
Array B: [1 2 3 4]

Addition:
[11 22 33 44]

Subtraction:
[ 9 18 27 36]

Multiplication:
[ 10  40  90 160]

Division:
[10. 10. 10. 10.]

Element-wise Power:
[     10     400   27000 2560000]

Modulo Operation:
[0 0 0 0]


## Q8. Matrix Multiplication

In [8]:
# Import NumPy library
import numpy as np

# Create two 3x3 matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Display matrices
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

# Element-wise multiplication
print("\nElement-wise Multiplication:")
print(A * B)

# Matrix multiplication
print("\nMatrix Multiplication:")
print(A @ B)

# Difference:
# * performs multiplication between corresponding elements.
# @ performs actual matrix multiplication.

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


## Q9. Combined - Properties + Operations + Indexing

In [9]:
# Import NumPy library
import numpy as np

# Generate a 6x6 matrix with random numbers
matrix = np.random.randn(6, 6)

# Display the matrix
print("Generated Matrix:\n")
print(matrix)

# Print basic properties
print("\nShape:", matrix.shape)
print("Size:", matrix.size)
print("Data Type:", matrix.dtype)

# Find maximum and minimum value indices
print("\nIndex of Maximum Value:", np.unravel_index(np.argmax(matrix), matrix.shape))
print("Index of Minimum Value:", np.unravel_index(np.argmin(matrix), matrix.shape))

# Extract top-left 3x3 submatrix
print("\nTop Left 3x3 Submatrix:")
print(matrix[:3, :3])

# Replace negative values with absolute values
matrix = np.abs(matrix)

# Print modified matrix
print("\nMatrix After Replacing Negative Values:")
print(matrix)

# Print mean
print("\nMean of Modified Matrix:", matrix.mean())

Generated Matrix:

[[-1.01503831  0.50573743 -0.21545815 -0.29179852  0.15976526 -0.32726107]
 [-1.17433363 -0.26654367  1.0687332   0.77534898  0.79709845 -0.76378287]
 [ 2.0285908  -1.40727977  0.1347643  -1.79971154  0.50529148  0.18056359]
 [ 1.06963348 -0.64728497 -1.02933322  1.21101712  1.77872489 -0.25000663]
 [-0.52570566 -0.38741925  1.11474328 -0.27933739  0.33762778 -0.11010271]
 [ 0.3953083  -1.82652768 -1.34581525  0.1857793  -1.51938691  0.86401493]]

Shape: (6, 6)
Size: 36
Data Type: float64

Index of Maximum Value: (np.int64(2), np.int64(0))
Index of Minimum Value: (np.int64(5), np.int64(1))

Top Left 3x3 Submatrix:
[[-1.01503831  0.50573743 -0.21545815]
 [-1.17433363 -0.26654367  1.0687332 ]
 [ 2.0285908  -1.40727977  0.1347643 ]]

Matrix After Replacing Negative Values:
[[1.01503831 0.50573743 0.21545815 0.29179852 0.15976526 0.32726107]
 [1.17433363 0.26654367 1.0687332  0.77534898 0.79709845 0.76378287]
 [2.0285908  1.40727977 0.1347643  1.79971154 0.50529148 0.180

## Q10. Mini Project - Student Performance Analysis

In [10]:
# Import NumPy library
import numpy as np

# Generate marks for 10 students in 5 subjects
marks = np.random.randint(30, 101, size=(10, 5))

# Display marks
print("Student Marks:\n")
print(marks)

# Calculate total marks
total_marks = marks.sum(axis=1)

# Calculate average marks
average_marks = marks.mean(axis=1)

print("\nTotal Marks of Each Student:")
print(total_marks)

print("\nAverage Marks of Each Student:")
print(average_marks)

# Find highest and lowest scorer
highest = np.argmax(total_marks)
lowest = np.argmin(total_marks)

print("\nStudent with Highest Total Marks:", highest + 1)
print("Total Marks:", total_marks[highest])

print("\nStudent with Lowest Total Marks:", lowest + 1)
print("Total Marks:", total_marks[lowest])

# Overall class statistics
print("\nClass Mean:", marks.mean())
print("Class Standard Deviation:", marks.std())

# Extract marks of top 3 students
top3 = np.argsort(total_marks)[-3:]

print("\nTop 3 Students (Marks):")
print(marks[top3])

# The array is already in 2D format, so reshaping is not required.
# We used indexing to display the marks of the top 3 students.

Student Marks:

[[68 34 63 67 89]
 [63 42 38 42 97]
 [92 36 48 43 83]
 [72 78 68 68 60]
 [56 86 35 68 35]
 [59 90 45 67 32]
 [89 91 49 66 41]
 [80 30 61 61 52]
 [84 59 60 58 35]
 [60 46 40 53 49]]

Total Marks of Each Student:
[321 282 302 346 280 293 336 284 296 248]

Average Marks of Each Student:
[64.2 56.4 60.4 69.2 56.  58.6 67.2 56.8 59.2 49.6]

Student with Highest Total Marks: 4
Total Marks: 346

Student with Lowest Total Marks: 10
Total Marks: 248

Class Mean: 59.76
Class Standard Deviation: 18.399521732914693

Top 3 Students (Marks):
[[68 34 63 67 89]
 [89 91 49 66 41]
 [72 78 68 68 60]]
